# Generated by Django 5.2 on 2025-04-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('UNIT', 'Unit/Piece'), ('TON', 'Tonne'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('SACK', 'Sack'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('BARREL', 'Barrel'), ('HECTOLITRE', 'Hectolitre'), ('M3', 'Cubic meter'), ('OTHER', 'Other')], default='UNIT', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('BROKEN', 'Broken')], default='NEW', max_length=10)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('service_due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('UNIT', 'Unit/Piece'), ('TON', 'Tonne'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('SACK', 'Sack'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('BARREL', 'Barrel'), ('HECTOLITRE', 'Hectolitre'), ('M3', 'Cubic meter'), ('OTHER', 'Other')], default='UNIT', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('livestock_type', models.CharField(choices=[('CATTLE', 'Cattle'), ('SHEEP', 'Sheep'), ('GOAT', 'Goat'), ('POULTRY', 'Poultry'), ('SWINE', 'Swine'), ('EQUINE', 'Equine'), ('RABBITS', 'Rabbits'), ('ALPACA', 'Alpaca'), ('LAMA', 'Lama'), ('BUFFALO', 'Buffalo'), ('DEER', 'Deer'), ('CAMEL', 'Camel'), ('BISON', 'Bison'), ('FISH', 'Fish'), ('PIGEON', 'Pigeon'), ('TURKEY', 'Turkey'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('custom_livestock_type', models.CharField(blank=True, max_length=100, null=True)),
                ('feeding_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('UNIT', 'Unit/Piece'), ('TON', 'Tonne'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('SACK', 'Sack'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('BARREL', 'Barrel'), ('HECTOLITRE', 'Hectolitre'), ('M3', 'Cubic meter'), ('OTHER', 'Other')], default='UNIT', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fertilizer_type', models.CharField(choices=[('NITROGEN', 'Nitrogen-based'), ('PHOSPHORUS', 'Phosphorus-based'), ('POTASSIUM', 'Potassium-based'), ('COMPOSITE', 'Composite'), ('LIQUID', 'Liquid'), ('ORGANIC', 'Organic'), ('INORGANIC', 'Inorganic'), ('BIOLOGICAL', 'Biological'), ('SLOW_RELEASE', 'Slow-release'), ('MINERAL', 'Mineral-based'), ('COMPOST', 'Compost'), ('FOLIAR', 'Foliar'), ('MICRONUTRIENT', 'Micronutrient'), ('LIQUID_FERTILIZER', 'Liquid Fertilizer'), ('OTHER', 'Other')], default='OTHER', max_length=100)),
                ('custom_fertilizer_type', models.CharField(blank=True, max_length=100, null=True)),
                ('application_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pesticide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('UNIT', 'Unit/Piece'), ('TON', 'Tonne'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('SACK', 'Sack'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('BARREL', 'Barrel'), ('HECTOLITRE', 'Hectolitre'), ('M3', 'Cubic meter'), ('OTHER', 'Other')], default='UNIT', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pesticide_type', models.CharField(choices=[('INSECTICIDE', 'Insecticide'), ('HERBICIDE', 'Herbicide'), ('FUNGICIDE', 'Fungicide'), ('RODENTICIDE', 'Rodenticide'), ('BACTERICIDE', 'Bactericide'), ('NEMATICIDE', 'Nematicide'), ('ACARICIDE', 'Acaricide')], max_length=100)),
                ('application_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_of_measure', models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('L', 'Litre'), ('ML', 'Millilitre'), ('UNIT', 'Unit/Piece'), ('TON', 'Tonne'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('SACK', 'Sack'), ('TRAY', 'Tray'), ('BOTTLE', 'Bottle'), ('BARREL', 'Barrel'), ('HECTOLITRE', 'Hectolitre'), ('M3', 'Cubic meter'), ('OTHER', 'Other')], default='UNIT', max_length=20)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crop_type', models.CharField(choices=[('CEREAL', 'Cereal'), ('LEGUME', 'Legume'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('TUBER', 'Tuber'), ('ROOT', 'Root'), ('LEAFY', 'Leafy'), ('NUT', 'Nut'), ('HERB', 'Herb'), ('FLOWER', 'Flower')], default='VEGETABLE', max_length=100)),
                ('sowing_instructions', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
