# Generated by Django 5.2 on 2025-04-18 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
    ]
