# Generated by Django 5.2 on 2025-04-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0028_remove_crop_seed_cost_per_ton_and_more'),
        ('resources', '0002_auto_20250418_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='seed',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.crop'),
        ),
        migrations.CreateModel(
            name='SeedUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('usage_date', models.DateField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crops.plantingfield')),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.seed')),
            ],
        ),
    ]
