# Generated by Django 5.2 on 2025-04-19 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0028_remove_crop_seed_cost_per_ton_and_more'),
        ('resources', '0003_remove_seed_crop_type_remove_seed_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='crop',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.crop'),
        ),
    ]
