# Generated by Django 5.2 on 2025-04-19 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_seed_crop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seed',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='supplier',
        ),
    ]
