# Generated by Django 5.2 on 2025-04-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_remove_seed_purchase_date_remove_seed_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedusage',
            name='quantity_used',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
