# Generated by Django 5.2 on 2025-04-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_alter_seedusage_quantity_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='price_per_unit',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='last_service_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='service_due_date',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='unit_of_measure',
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
