# Generated by Django 5.2 on 2025-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_maintenancerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='custom_fertilizer_type',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='purchase_date',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='supplier',
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='unit_of_measure',
            field=models.CharField(choices=[('L', 'Litre'), ('ML', 'Millilitre'), ('UNIT', 'Unit/Piece'), ('BOTTLE', 'Bottle'), ('HECTOLITRE', 'Hectolitre'), ('M3', 'Cubic meter'), ('OTHER', 'Other')], default='UNIT', max_length=20),
        ),
    ]
