# Generated by Django 5.2 on 2025-04-19 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0028_remove_crop_seed_cost_per_ton_and_more'),
        ('resources', '0009_remove_fertilizer_custom_fertilizer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('amount_used', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('fertilizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='resources.fertilizer')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.plantingfield')),
            ],
        ),
    ]
