# Generated by Django 5.2 on 2025-04-19 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0028_remove_crop_seed_cost_per_ton_and_more'),
        ('resources', '0011_remove_pesticide_expiry_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesticideUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('date_of_application', models.DateField(auto_now_add=True)),
                ('method_of_application', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.plantingfield')),
                ('pesticide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='resources.pesticide')),
            ],
        ),
    ]
