# Generated by Django 5.2 on 2025-04-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_pesticideusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='livestock_type',
        ),
        migrations.AddField(
            model_name='feed',
            name='food_type',
            field=models.CharField(choices=[('GRASS', 'Grass'), ('HAY', 'Hay'), ('GRAINS', 'Grains'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('SEEDS', 'Seeds'), ('FISHMEAL', 'Fishmeal'), ('OTHER', 'Other')], default='GRASS', max_length=50),
        ),
        migrations.AlterField(
            model_name='feed',
            name='unit_of_measure',
            field=models.CharField(choices=[('KG', 'Kilogram'), ('G', 'Gram'), ('UNIT', 'Unit/Piece'), ('TON', 'Tonne'), ('BAG', 'Bag'), ('BOX', 'Box'), ('PACK', 'Pack'), ('OTHER', 'Other')], default='UNIT', max_length=20),
        ),
    ]
