# Generated by Django 5.2 on 2025-04-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_remove_feed_livestock_type_feed_food_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='custom_livestock_type',
        ),
    ]
