# Generated by Django 5.2 on 2025-04-19 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_remove_feed_custom_livestock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='supplier',
        ),
    ]
