# Generated by Django 5.2 on 2025-04-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0029_remove_plantingfieldtransaction_buyer_and_more'),
        ('resources', '0015_remove_feed_expiry_date_remove_feed_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.FloatField()),
                ('date_used', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='resources.feed')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield')),
            ],
        ),
    ]
