# Generated by Django 5.2 on 2025-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0017_alter_feed_name_alter_feed_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
