# Generated by Django 5.2 on 2025-04-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0018_alter_feed_price_per_unit_alter_feed_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
