# Generated by Django 5.2 on 2025-04-25 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0021_alter_feed_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='name',
            field=models.CharField(default='Unnamed Feed', max_length=100),
        ),
    ]
