# Generated by Django 5.2 on 2025-04-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0023_alter_feed_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('USED', 'Used'), ('BROKEN', 'Broken')], default='NEW', max_length=6),
        ),
    ]
