# Generated by Django 5.1.2 on 2025-05-03 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0029_remove_plantingfieldtransaction_buyer_and_more'),
        ('resources', '0025_alter_pesticideusage_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesticideusage',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.plantingfield'),
        ),
    ]
