# Generated by Django 5.1.2 on 2025-05-03 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0027_alter_fertilizerusage_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerusage',
            name='date_applied',
            field=models.DateField(auto_now_add=True),
        ),
    ]
