# Generated by Django 5.1.2 on 2025-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0028_alter_fertilizerusage_date_applied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerusage',
            name='date_applied',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pesticideusage',
            name='date_of_application',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
