# Generated by Django 5.1.2 on 2025-06-11 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0029_remove_plantingfieldtransaction_buyer_and_more'),
        ('resources', '0030_alter_fertilizerusage_date_applied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seed',
            name='crop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.crop'),
        ),
    ]
