# Generated by Django 5.2 on 2025-04-11 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0003_remove_field_latitude_remove_field_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], default='MALE', max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('grazing_field', models.ForeignKey(blank=True, limit_choices_to={'field_type': 'GRAZING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.field')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livestock.species')),
            ],
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_status', models.CharField(blank=True, choices=[('HEALTHY', 'Healthy'), ('ILL', 'Ill'), ('INJURED', 'Injured'), ('VACCINATED', 'Vaccinated'), ('RECOVERING', 'Recovering'), ('QUARANTINED', 'Quarantined'), ('UNDER_OBSERVATION', 'Under Observation'), ('DECEASED', 'Deceased')], max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='livestock.livestock')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(choices=[('RABIES', 'Rabies'), ('BOVINE_TB', 'Bovine Tuberculosis'), ('BRUCELLOSIS', 'Brucellosis'), ('IBR', 'Infectious Bovine Rhinotracheitis'), ('BVD', 'Bovine Viral Diarrhea'), ('LEPTOSPIROSIS', 'Leptospirosis'), ('BLACKLEG', 'Blackleg'), ('FOOT_AND_MOUTH', 'Foot and Mouth Disease'), ('ANTHRAX', 'Anthrax'), ('BLUETONGUE', 'Bluetongue'), ('SHEEP_POX', 'Sheep Pox'), ('OVINE_TACHENG', 'Ovine Tacheng'), ('SHEEP_ERYSIPELOTHRIX', 'Erysipelothrix (Sheep)'), ('MASTITIS', 'Mastitis Vaccine'), ('CSF', 'Classical Swine Fever'), ('ASF', 'African Swine Fever'), ('SWINE_INFLUENZA', 'Swine Influenza'), ('TETANUS', 'Tetanus'), ('HOG_CHOLERA', 'Hog Cholera'), ('CHICKEN_POX', 'Chickenpox'), ('AVIAN_FLU', 'Avian Influenza'), ('NEWCASTLE_DISEASE', 'Newcastle Disease'), ('FOWL_POX', 'Fowl Pox'), ('SALMONELLOSIS', 'Salmonellosis'), ('CAMPYLOBACTERIOSIS', 'Campylobacteriosis'), ('PARVOVIRUS', 'Parvovirus'), ('LEUKEMIA', 'Leukemia'), ('TUBERCULOSIS', 'Tuberculosis (Bovine)'), ('EPM', 'Equine Protozoal Myeloencephalitis'), ('ROTAVIRUS', 'Rotavirus'), ('CALF_DIARRHEA', 'Calf Diarrhea Vaccine'), ('HEARTWORM', 'Heartworm Vaccine'), ('FLEA_TICK', 'Flea and Tick Prevention'), ('INFLUENZA_A', 'Influenza A Vaccine'), ('RHINO', 'Rhinovirus'), ('OTHER', 'Other')], max_length=100)),
                ('vaccination_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('custom_vaccination_name', models.CharField(blank=True, max_length=100, null=True)),
                ('livestock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='livestock.livestock')),
            ],
        ),
    ]
