# Generated by Django 5.2 on 2025-04-16 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livestocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='species',
            name='average_height',
            field=models.CharField(blank=True, choices=[('<0.5', 'Less than 0.5m'), ('0.5-1', '0.5-1m'), ('1-3', '1-3m'), ('3-5', '3-5m'), ('>5', 'More than 5m')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='average_weight',
            field=models.CharField(blank=True, choices=[('<10', 'Less than 10kg'), ('10-50', '10-50kg'), ('50-100', '50-100kg'), ('100-500', '100-500kg'), ('>500', 'More than 500kg')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='behavior',
            field=models.CharField(blank=True, choices=[('SOCIAL', 'Social'), ('SOLITARY', 'Solitary'), ('MIGRATORY', 'Migratory'), ('NOCTURNAL', 'Nocturnal'), ('DIURNAL', 'Diurnal')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='conservation_status',
            field=models.CharField(choices=[('LC', 'Least Concern'), ('NT', 'Near Threatened'), ('VU', 'Vulnerable'), ('EN', 'Endangered'), ('CR', 'Critically Endangered'), ('EX', 'Extinct'), ('EW', 'Extinct in the Wild')], default='LC', max_length=2),
        ),
        migrations.AddField(
            model_name='species',
            name='diet',
            field=models.CharField(blank=True, choices=[('HERBIVORE', 'Herbivore'), ('CARNIVORE', 'Carnivore'), ('OMNIVORE', 'Omnivore'), ('INSECTIVORE', 'Insectivore'), ('FRUGIVORE', 'Frugivore'), ('NECROPHAGY', 'Necrophagy')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='endangered_status',
            field=models.CharField(blank=True, choices=[('CRITICALLY_ENDANGERED', 'Critically Endangered'), ('ENDANGERED', 'Endangered'), ('VULNERABLE', 'Vulnerable'), ('NEAR_THREATENED', 'Near Threatened'), ('LEAST_CONCERN', 'Least Concern'), ('DATA_DEFICIENT', 'Data Deficient'), ('NOT_EVALUATED', 'Not Evaluated'), ('UNKNOWN', 'Unknown')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='genus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='habitat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='kingdom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='lifespan',
            field=models.IntegerField(blank=True, choices=[(1, 'Less than 1 year'), (2, '1-5 years'), (3, '6-10 years'), (4, '11-20 years'), (5, '21-50 years'), (6, 'More than 50 years')], null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='mating_season',
            field=models.CharField(blank=True, choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('AUTUMN', 'Autumn'), ('WINTER', 'Winter'), ('YEAR_ROUND', 'Year-Round'), ('UNKNOWN', 'Unknown')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='range',
            field=models.CharField(blank=True, choices=[('AFRICA', 'Africa'), ('ASIA', 'Asia'), ('EUROPE', 'Europe'), ('NORTH_AMERICA', 'North America'), ('SOUTH_AMERICA', 'South America'), ('OCEANIA', 'Oceania'), ('ANTARCTICA', 'Antarctica'), ('GLOBAL', 'Global')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='reproduction',
            field=models.CharField(blank=True, choices=[('OVIPAROUS', 'Oviparous'), ('VIVIPAROUS', 'Viviparous'), ('OVOVIVIPAROUS', 'Ovoviviparous')], max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
