# Generated by Django 5.2 on 2025-04-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_livestock_user_species_average_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='cost_of_treatment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='is_critical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='next_checkup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='symptoms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
