# Generated by Django 5.2 on 2025-04-16 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_alter_field_planting_date'),
        ('livestock', '0003_healthrecord_cost_of_treatment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.ForeignKey(blank=True, limit_choices_to={'field_type': 'GRAZING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.field')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.species')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
