# Generated by Django 5.2 on 2025-04-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0004_herd'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestock',
            name='herd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livestock', to='livestock.herd'),
        ),
    ]
