# Generated by Django 5.2 on 2025-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0005_livestock_herd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthrecord',
            name='is_critical',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='severity_level',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10, null=True),
        ),
    ]
