# Generated by Django 5.2 on 2025-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0007_vaccinationrecord_cost_of_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved')], default='approved', max_length=10),
        ),
    ]
