# Generated by Django 5.2 on 2025-04-17 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_remove_field_crop_remove_field_user_grazingfield_and_more'),
        ('livestock', '0008_species_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herd',
            name='field',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_type': 'GRAZING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='grazing_field',
            field=models.ForeignKey(blank=True, limit_choices_to={'field_type': 'GRAZING'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
    ]
