# Generated by Django 5.2 on 2025-04-17 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0015_remove_grazingfield_status'),
        ('livestock', '0009_alter_herd_field_alter_livestock_grazing_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herd',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
    ]
