# Generated by Django 5.2 on 2025-04-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0010_alter_herd_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='species',
            name='products',
            field=models.ManyToManyField(related_name='species', to='livestock.product'),
        ),
    ]
