# Generated by Django 5.2 on 2025-04-18 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0023_remove_grazingfield_animal_count'),
        ('livestock', '0011_product_species_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='grazing_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
    ]
