# Generated by Django 5.2 on 2025-04-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0029_remove_plantingfieldtransaction_buyer_and_more'),
        ('livestock', '0012_alter_livestock_grazing_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herd',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
        migrations.AlterField(
            model_name='herd',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.species'),
        ),
        migrations.AlterField(
            model_name='livestock',
            name='grazing_field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
    ]
