# Generated by Django 5.2 on 2025-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0013_alter_herd_field_alter_herd_species_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
