# Generated by Django 5.2 on 2025-04-24 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0029_remove_plantingfieldtransaction_buyer_and_more'),
        ('livestock', '0014_alter_livestock_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livestock',
            name='grazing_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.grazingfield'),
        ),
    ]
