# Generated by Django 5.2 on 2025-04-25 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0015_alter_livestock_grazing_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='products',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
