# Generated by Django 5.2 on 2025-04-18 12:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0019_remove_harvestsummary_archived_and_more'),
        ('livestock', '0010_alter_herd_field'),
        ('resources', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_type', models.CharField(choices=[('PLANTING', 'Planting'), ('HARVESTING', 'Harvesting'), ('IRRIGATION', 'Irrigation'), ('MAINTENANCE', 'Maintenance'), ('FERTILIZING', 'Fertilizing'), ('PEST_CONTROL', 'Pest Control'), ('FEEDING', 'Feeding'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('start_date', models.DateTimeField(default=datetime.date.today)),
                ('due_date', models.DateTimeField()),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('related_crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('related_equipment', models.ManyToManyField(blank=True, to='resources.equipment')),
                ('related_livestock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='livestock.livestock')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
