# Generated by Django 5.1.2 on 2025-06-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0030_alter_fertilizerusage_date_applied_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='related_equipment',
        ),
        migrations.AddField(
            model_name='task',
            name='related_equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.equipment'),
        ),
    ]
