# Generated by Django 5.2 on 2025-04-25 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_dailybalance_delete_financialrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybalance',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AddIndex(
            model_name='dailybalance',
            index=models.Index(fields=['user', 'date'], name='finance_dai_user_id_b380dc_idx'),
        ),
    ]
