# Generated by Django 5.2 on 2025-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_dailybalance_date_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dailybalance',
            name='finance_dai_user_id_b380dc_idx',
        ),
        migrations.AlterField(
            model_name='dailybalance',
            name='date',
            field=models.DateField(),
        ),
    ]
