# Generated by Django 5.2 on 2025-04-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('crop_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FieldForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('area', models.FloatField()),
                ('crop_type', models.CharField(max_length=200)),
            ],
        ),
    ]
