# Generated by Django 5.2 on 2025-04-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_crop_delete_fieldform_remove_field_crop_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='field',
            name='longitude',
        ),
    ]
