# Generated by Django 5.2 on 2025-04-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0004_crop_user_field_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='address',
        ),
        migrations.AddField(
            model_name='field',
            name='estimated_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='grazing_rest_days',
            field=models.PositiveIntegerField(blank=True, help_text='Rest days after grazing before reuse', null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='light_profile',
            field=models.CharField(blank=True, choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL_SHADE', 'Partial Shade'), ('FULL_SHADE', 'Full Shade')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('FALLOW', 'Fallow'), ('LEASED', 'Leased'), ('OTHER', 'Other')], default='ACTIVE', max_length=10),
        ),
    ]
