# Generated by Django 5.2 on 2025-04-12 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0005_remove_field_address_field_estimated_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='harvesting_time',
        ),
        migrations.AddField(
            model_name='crop',
            name='average_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='botanical_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='days_to_emerge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='days_to_flower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='days_to_maturity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='estimated_revenue_per_harvest_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='estimated_yield_per_ha',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvest_unit',
            field=models.CharField(blank=True, choices=[('KG', 'Kilogram'), ('TON', 'Ton'), ('PIECE', 'Piece'), ('LITER', 'Liter'), ('METER', 'Meter'), ('BUNCH', 'Bunch'), ('BUSHEL', 'Bushel'), ('CRATE', 'Crate'), ('CARTON', 'Carton'), ('GALLON', 'Gallon'), ('BAG', 'Bag'), ('PALLET', 'Pallet'), ('SACK', 'Sack'), ('TUB', 'Tub'), ('TONNE', 'Tonne'), ('KG_PER_HA', 'Kilogram per Hectare'), ('BUNDLE', 'Bundle'), ('PACK', 'Pack'), ('STEM', 'Stem')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='harvesting_time_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='plant_spacing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='planting_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='row_spacing',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
