# Generated by Django 5.2 on 2025-04-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0006_remove_crop_harvesting_time_crop_average_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='planting_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
