# Generated by Django 5.2 on 2025-04-17 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0007_alter_field_planting_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='user',
        ),
    ]
