# Generated by Django 5.2 on 2025-04-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0008_remove_crop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('KWS', 'KWS'), ('PIONEER', 'Pioneer'), ('SYNGENTA', 'Syngenta'), ('LIMAGRAIN', 'Limagrain'), ('DEKALB', 'Dekalb'), ('BASF', 'BASF'), ('RAGT', 'RAGT'), ('BAYER', 'Bayer'), ('AGROMA', 'Agroma'), ('MONSANTO', 'Monsanto'), ('OTHERS', 'Others')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='variety_type',
            field=models.CharField(blank=True, choices=[('HYBRID', 'Hybrid'), ('OPEN_POLLINATED', 'Open Pollinated'), ('EARLY', 'Early Maturing'), ('LATE', 'Late Maturing'), ('DROUGHT_TOLERANT', 'Drought Tolerant'), ('DISEASE_RESISTANT', 'Disease Resistant'), ('HIGH_YIELD', 'High Yield'), ('SILAGE', 'Silage'), ('GRAIN', 'Grain'), ('FODDER', 'Fodder'), ('ORGANIC', 'Organic'), ('CONVENTIONAL', 'Conventional')], max_length=100, null=True),
        ),
    ]
