# Generated by Django 5.2 on 2025-04-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0010_crop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='animal_count',
            field=models.PositiveIntegerField(blank=True, help_text='Number of animals on this field', null=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
