# Generated by Django 5.2 on 2025-04-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0011_field_animal_count_alter_crop_manufacturer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='field',
            name='user',
        ),
        migrations.CreateModel(
            name='GrazingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('grazing_rest_days', models.PositiveIntegerField(blank=True, help_text='Rest days after grazing before reuse', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FALLOW', 'Fallow'), ('LEASED', 'Leased'), ('OTHER', 'Other')], default='ACTIVE', max_length=10)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('animal_count', models.PositiveIntegerField(blank=True, help_text='Number of animals on this field', null=True)),
                ('water_source', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlantingField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.FloatField()),
                ('soil_type', models.CharField(choices=[('LOAM', 'Loam'), ('CLAY', 'Clay'), ('SILT', 'Silt'), ('SAND', 'Sand'), ('PEAT', 'Peat')], default='LOAM', max_length=10)),
                ('planting_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FALLOW', 'Fallow'), ('LEASED', 'Leased'), ('OTHER', 'Other')], default='ACTIVE', max_length=10)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('light_profile', models.CharField(blank=True, choices=[('FULL_SUN', 'Full Sun'), ('PARTIAL_SHADE', 'Partial Shade'), ('FULL_SHADE', 'Full Shade')], max_length=15, null=True)),
                ('crop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.crop')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
