# Generated by Django 5.2 on 2025-04-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0012_remove_field_crop_remove_field_user_grazingfield_and_more'),
        ('livestock', '0009_alter_herd_field_alter_livestock_grazing_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Field',
        ),
    ]
