# Generated by Django 5.2 on 2025-04-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0013_delete_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingfield',
            name='status',
        ),
    ]
