# Generated by Django 5.2 on 2025-04-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0014_remove_plantingfield_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grazingfield',
            name='status',
        ),
    ]
