# Generated by Django 5.2 on 2025-04-17 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0015_remove_grazingfield_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('plant_height', models.FloatField(blank=True, null=True)),
                ('plant_health', models.CharField(blank=True, max_length=255, null=True)),
                ('flowering_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('BEGINNING', 'Beginning of Flowering'), ('PEAK', 'Full Flowering'), ('ENDING', 'End of Flowering'), ('COMPLETED', 'Flowering Completed')], default='NOT_STARTED', max_length=50)),
                ('maturity_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('BEGINNING', 'Beginning of Maturity'), ('HALFWAY', 'Halfway to Maturity'), ('NEAR_COMPLETION', 'Near Completion'), ('COMPLETED', 'Fully Matured')], default='NOT_STARTED', max_length=50)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('planting_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='crops.plantingfield')),
            ],
        ),
    ]
