# Generated by Django 5.2 on 2025-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0016_plantingreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingreport',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
