# Generated by Django 5.2 on 2025-04-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0017_plantingreport_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantingfield',
            name='is_harvested',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='HarvestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20)),
                ('yield_in_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_ton', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvest_summaries', to='crops.plantingfield')),
            ],
        ),
    ]
