# Generated by Django 5.2 on 2025-04-18 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0018_plantingfield_is_harvested_harvestsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestsummary',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='plantingfield',
            name='is_harvested',
        ),
    ]
