# Generated by Django 5.2 on 2025-04-18 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0020_plantingfield_is_active_plantingfieldtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingfield',
            name='is_active',
        ),
        migrations.AddField(
            model_name='plantingfieldtransaction',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plantingfieldtransaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
