# Generated by Django 5.2 on 2025-04-18 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0021_remove_plantingfield_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantingfieldtransaction',
            old_name='date',
            new_name='created_at',
        ),
    ]
