# Generated by Django 5.2 on 2025-04-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0022_rename_date_plantingfieldtransaction_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grazingfield',
            name='animal_count',
        ),
    ]
