# Generated by Django 5.2 on 2025-04-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0024_grazingfieldtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='harvest_unit',
        ),
    ]
