# Generated by Django 5.2 on 2025-04-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0025_remove_crop_harvest_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='seed_cost_per_ton',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='seed_quantity_in_tons',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
