# Generated by Django 5.2 on 2025-04-19 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0026_crop_seed_cost_per_ton_crop_seed_quantity_in_tons'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity_in_tons', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_purchases', to='crops.crop')),
            ],
        ),
    ]
