# Generated by Django 5.2 on 2025-04-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0028_remove_crop_seed_cost_per_ton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantingfieldtransaction',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='plantingfieldtransaction',
            name='planting_field',
        ),
        migrations.RemoveField(
            model_name='plantingfieldtransaction',
            name='seller',
        ),
        migrations.DeleteModel(
            name='GrazingFieldTransaction',
        ),
        migrations.DeleteModel(
            name='PlantingFieldTransaction',
        ),
    ]
